const module = 'APP';

const INITIAL_SETUP_PENDING = `${module}/INITIAL_SETUP_PENDING`;
const INITIAL_SETUP_SUCCESS = `${module}/INITIAL_SETUP_SUCCESS`;
const INITIAL_SETUP_ERROR = `${module}/INITIAL_SETUP_ERROR`;

export { INITIAL_SETUP_PENDING, INITIAL_SETUP_SUCCESS, INITIAL_SETUP_ERROR };
